# Project-wide Gradle settings.

# Specifies the JVM arguments used for the daemon process.
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8

# AndroidX package structure
android.useAndroidX=true

# Custom AAPT2 binary location for transparent cross-platform execution
android.aapt2FromMavenOverride=/root/android-sdk/build-tools/35.0.0/aapt2
